import type { Candidate, MarketSignal, DiligenceReport, PhaseStep, Leader } from '@/types';

// ── Candidates ─────────────────────────────────────────────────────────────────
export const CANDIDATES: Candidate[] = [
  {
    id: 'cand-001',
    name: 'Ashburn Core Campus',
    operator: 'Equinix',
    region: 'NOVA',
    market: 'Northern Virginia',
    state: 'VA',
    totalMW: 120,
    availableMW: 22,
    deliverableMW: 18,
    expandableMW: 80,
    status: 'available',
    tier: 3,
    coolingTypes: ['liquid', 'air'],
    pue: 1.35,
    redundancy: 'N+1',
    utilityProvider: 'Dominion Energy',
    interconnectStatus: 'operational',
    availableMonths: 4,
    costPerKwMonth: 148,
    certifications: ['SOC2', 'ISO27001', 'PCI-DSS'],
    carriers: ['Zayo', 'Lumen', 'Cogent', 'Telia'],
    fiberRoutes: 6,
    gridRiskLevel: 'low',
    permittingRisk: 'low',
    dataConfidence: 94,
    lastVerified: '2026-04-10',
    offMarket: false,
    renewablePercent: 60,
  },
  {
    id: 'cand-002',
    name: 'Columbus Hyperscale Campus',
    operator: 'DataBank',
    region: 'CMH',
    market: 'Columbus, OH',
    state: 'OH',
    totalMW: 200,
    availableMW: 45,
    deliverableMW: 38,
    expandableMW: 160,
    status: 'available',
    tier: 3,
    coolingTypes: ['air', 'liquid'],
    pue: 1.42,
    redundancy: 'N+1',
    utilityProvider: 'AEP Ohio',
    interconnectStatus: 'approved',
    interconnectTimelineMonths: 6,
    availableMonths: 8,
    costPerKwMonth: 126,
    certifications: ['SOC2', 'ISO27001'],
    carriers: ['AT&T', 'Zayo', 'Windstream'],
    fiberRoutes: 4,
    gridRiskLevel: 'low',
    permittingRisk: 'low',
    dataConfidence: 88,
    lastVerified: '2026-04-05',
    offMarket: false,
    renewablePercent: 45,
  },
  {
    id: 'cand-003',
    name: 'Irving Logistics District',
    operator: 'Aligned Data Centers',
    region: 'DFW',
    market: 'Dallas-Fort Worth',
    state: 'TX',
    totalMW: 300,
    availableMW: 60,
    deliverableMW: 32,
    expandableMW: 220,
    status: 'available',
    tier: 3,
    coolingTypes: ['liquid', 'immersion'],
    pue: 1.28,
    redundancy: 'N+1',
    utilityProvider: 'Oncor / ERCOT',
    interconnectStatus: 'pending',
    interconnectTimelineMonths: 14,
    availableMonths: 18,
    costPerKwMonth: 132,
    certifications: ['SOC2'],
    carriers: ['AT&T', 'Lumen', 'Zayo'],
    fiberRoutes: 5,
    gridRiskLevel: 'medium',
    permittingRisk: 'low',
    dataConfidence: 79,
    lastVerified: '2026-03-28',
    offMarket: false,
    renewablePercent: 20,
  },
  {
    id: 'cand-004',
    name: 'Chicago Premium Colocation',
    operator: 'Digital Realty',
    region: 'CHI',
    market: 'Chicago, IL',
    state: 'IL',
    totalMW: 80,
    availableMW: 9,
    deliverableMW: 9,
    expandableMW: 40,
    status: 'limited',
    tier: 4,
    coolingTypes: ['immersion', 'liquid', 'air'],
    pue: 1.22,
    redundancy: '2N',
    utilityProvider: 'ComEd',
    interconnectStatus: 'operational',
    availableMonths: 2,
    costPerKwMonth: 168,
    certifications: ['SOC2', 'ISO27001', 'PCI-DSS', 'HIPAA'],
    carriers: ['Zayo', 'Cogent', 'Telia', 'AT&T', 'Lumen'],
    fiberRoutes: 8,
    gridRiskLevel: 'low',
    permittingRisk: 'low',
    dataConfidence: 97,
    lastVerified: '2026-04-14',
    offMarket: false,
    renewablePercent: 75,
  },
  {
    id: 'cand-005',
    name: 'Atlanta Peachtree Campus',
    operator: 'QTS Realty',
    region: 'ATL',
    market: 'Atlanta, GA',
    state: 'GA',
    totalMW: 250,
    availableMW: 28,
    deliverableMW: 25,
    expandableMW: 180,
    status: 'available',
    tier: 3,
    coolingTypes: ['air', 'liquid'],
    pue: 1.45,
    redundancy: 'N+1',
    utilityProvider: 'Georgia Power',
    interconnectStatus: 'approved',
    interconnectTimelineMonths: 8,
    availableMonths: 12,
    costPerKwMonth: 119,
    certifications: ['SOC2', 'ISO27001'],
    carriers: ['AT&T', 'Zayo', 'Cox'],
    fiberRoutes: 4,
    gridRiskLevel: 'low',
    permittingRisk: 'medium',
    dataConfidence: 82,
    lastVerified: '2026-03-20',
    offMarket: false,
    renewablePercent: 30,
  },
  {
    id: 'cand-006',
    name: 'Hillsboro Off-Market Site',
    operator: 'Undisclosed',
    region: 'PDX',
    market: 'Portland, OR',
    state: 'OR',
    totalMW: 40,
    availableMW: 12,
    deliverableMW: 10,
    expandableMW: 30,
    status: 'available',
    tier: 3,
    coolingTypes: ['liquid', 'air'],
    pue: 1.31,
    redundancy: 'N+1',
    utilityProvider: 'PGE',
    interconnectStatus: 'approved',
    interconnectTimelineMonths: 5,
    availableMonths: 9,
    costPerKwMonth: 112,
    certifications: ['SOC2'],
    carriers: ['Zayo', 'Lumen'],
    fiberRoutes: 3,
    gridRiskLevel: 'low',
    permittingRisk: 'low',
    dataConfidence: 71,
    lastVerified: '2026-02-15',
    offMarket: true,
    renewablePercent: 95,
  },
  {
    id: 'cand-007',
    name: 'Phoenix Desert Campus',
    operator: 'CyrusOne',
    region: 'PHX',
    market: 'Phoenix, AZ',
    state: 'AZ',
    totalMW: 400,
    availableMW: 80,
    deliverableMW: 45,
    expandableMW: 300,
    status: 'development',
    tier: 2,
    coolingTypes: ['air'],
    pue: 1.58,
    redundancy: 'N',
    utilityProvider: 'APS',
    interconnectStatus: 'pending',
    interconnectTimelineMonths: 20,
    availableMonths: 26,
    costPerKwMonth: 108,
    certifications: [],
    carriers: ['CenturyLink', 'Cox'],
    fiberRoutes: 2,
    gridRiskLevel: 'high',
    permittingRisk: 'medium',
    dataConfidence: 62,
    lastVerified: '2026-01-30',
    offMarket: false,
    renewablePercent: 10,
  },
];

// ── Market Signals ─────────────────────────────────────────────────────────────
export const SIGNALS: MarketSignal[] = [
  {
    id: 'sig-001',
    category: 'GRID',
    signal: 'PJM interconnect queue delays extending to 36 months.',
    impact: 'AI-scale projects in the PJM footprint face extended timelines. Off-market sourcing essential.',
    timestamp: '2 hours ago',
    severity: 'High',
    region: 'NOVA',
    source: 'PJM Interconnection LLC',
    provenance: 'Official filing — FERC docket ER26-0412',
    tags: ['interconnect', 'pjm', 'ai-scale'],
    actionable: true,
  },
  {
    id: 'sig-002',
    category: 'POLICY',
    signal: 'New EU Data Sovereignty laws impacting cross-border AI training.',
    impact: 'Operators deploying across EU must validate data residency compliance before commitments.',
    timestamp: '6 hours ago',
    severity: 'Medium',
    region: 'EMEA',
    source: 'European Commission',
    provenance: 'EU Regulation 2026/417 — published April 2026',
    tags: ['compliance', 'eu', 'data-residency'],
    actionable: false,
  },
  {
    id: 'sig-003',
    category: 'CAPACITY',
    signal: 'Off-market 20MW capacity identified in secondary Ohio market.',
    impact: 'Pre-qualified colocation capacity available outside standard channels — window is 60–90 days.',
    timestamp: '1 day ago',
    severity: 'Low',
    region: 'CMH',
    source: 'InfraX Grid Intelligence',
    provenance: 'Proprietary operator network — verified April 14, 2026',
    tags: ['off-market', 'ohio', 'capacity'],
    actionable: true,
  },
  {
    id: 'sig-004',
    category: 'PRICING',
    signal: 'Northern Virginia colocation rates up 8% YoY. Tier III now averaging $152/kW/mo.',
    impact: 'Capital deployment in NOVA must re-model cost assumptions for 2026 commitments.',
    timestamp: '2 days ago',
    severity: 'Medium',
    region: 'NOVA',
    source: 'CBRE Data Center Advisory',
    provenance: 'Q1 2026 Market Report — published April 2026',
    tags: ['pricing', 'nova', 'colocation'],
    actionable: false,
  },
  {
    id: 'sig-005',
    category: 'SUPPLY',
    signal: 'ERCOT grid upgrade adds 4GW of transmission capacity in West Texas corridor.',
    impact: 'New renewable-backed capacity opens greenfield data center development opportunity in Permian Basin.',
    timestamp: '3 days ago',
    severity: 'Medium',
    region: 'DFW',
    source: 'ERCOT',
    provenance: 'ERCOT Transmission Planning Report — March 2026',
    tags: ['ercot', 'texas', 'renewable', 'expansion'],
    actionable: true,
  },
  {
    id: 'sig-006',
    category: 'DEMAND',
    signal: 'Hyperscaler reservation activity in Columbus up 340% YoY.',
    impact: 'Available capacity in CMH market under sustained pressure. Advance reservation recommended.',
    timestamp: '4 days ago',
    severity: 'High',
    region: 'CMH',
    source: 'InfraX Grid Intelligence',
    provenance: 'Operator survey — April 2026',
    tags: ['columbus', 'hyperscale', 'demand'],
    actionable: true,
  },
  {
    id: 'sig-007',
    category: 'GRID',
    signal: 'Dominion Energy substation headroom reduction in Loudoun County to 180MW total.',
    impact: 'Near-term capacity constraints for new deployments in core NOVA market. Secondary sites warranted.',
    timestamp: '5 days ago',
    severity: 'High',
    region: 'NOVA',
    source: 'Dominion Energy',
    provenance: 'Utility planning document — April 2026',
    tags: ['dominion', 'nova', 'substation', 'constraint'],
    actionable: true,
  },
];

// ── Trend data for charts ──────────────────────────────────────────────────────
export const PRICING_TREND = [
  { month: 'Oct', nova: 138, cmh: 118, dfw: 122 },
  { month: 'Nov', nova: 140, cmh: 120, dfw: 124 },
  { month: 'Dec', nova: 142, cmh: 121, dfw: 126 },
  { month: 'Jan', nova: 145, cmh: 122, dfw: 128 },
  { month: 'Feb', nova: 148, cmh: 124, dfw: 130 },
  { month: 'Mar', nova: 150, cmh: 125, dfw: 131 },
  { month: 'Apr', nova: 152, cmh: 126, dfw: 132 },
];

// ── Mandate timeline ───────────────────────────────────────────────────────────
export const MANDATE_PHASES: PhaseStep[] = [
  {
    phase: 'intake',
    label: 'Intake & Scoping',
    description: 'Structured requirement capture and constraint definition.',
    status: 'complete',
    deliverables: [
      { id: 'd-001', title: 'Requirements Document', description: 'Signed requirements spec', phase: 'intake', status: 'complete', owner: 'InfraX' },
      { id: 'd-002', title: 'Constraint Matrix', description: 'Hard vs soft constraints mapped', phase: 'intake', status: 'complete', owner: 'InfraX' },
    ],
  },
  {
    phase: 'modeling',
    label: 'InfraAlign™ Modeling',
    description: 'Physics-first feasibility modeling across target regions.',
    status: 'complete',
    deliverables: [
      { id: 'd-003', title: 'Feasibility Report', description: 'Regional feasibility scores', phase: 'modeling', status: 'complete', owner: 'InfraX' },
      { id: 'd-004', title: 'Constraint Analysis', description: 'Utility and interconnect mapping', phase: 'modeling', status: 'complete', owner: 'InfraX' },
    ],
  },
  {
    phase: 'shortlist',
    label: 'Candidate Shortlist',
    description: 'Ranked candidate set with scored fit analysis.',
    status: 'active',
    deliverables: [
      { id: 'd-005', title: 'Ranked Shortlist', description: 'Top 5 candidates with scores', phase: 'shortlist', status: 'in-progress', owner: 'InfraX' },
      { id: 'd-006', title: 'Site Visits', description: 'Physical validation of top 3', phase: 'shortlist', status: 'pending', owner: 'Client + InfraX' },
    ],
  },
  {
    phase: 'diligence',
    label: 'Technical Diligence',
    description: 'Deep-dive validation of utility commitments and operator capabilities.',
    status: 'upcoming',
    deliverables: [
      { id: 'd-007', title: 'Utility LOI Review', description: 'Interconnect commitment analysis', phase: 'diligence', status: 'pending', owner: 'InfraX' },
      { id: 'd-008', title: 'Operator Capability Audit', description: 'Technical capacity verification', phase: 'diligence', status: 'pending', owner: 'InfraX' },
    ],
  },
  {
    phase: 'negotiation',
    label: 'Commercial Negotiation',
    description: 'Data-backed term negotiation with selected operators.',
    status: 'upcoming',
    deliverables: [
      { id: 'd-009', title: 'Term Sheet Review', description: 'Commercial terms analysis', phase: 'negotiation', status: 'pending', owner: 'InfraX + Client' },
    ],
  },
  {
    phase: 'execution',
    label: 'Execution & Oversight',
    description: 'Deployment lifecycle management from LOI through power-on.',
    status: 'upcoming',
    deliverables: [
      { id: 'd-010', title: 'SLA Framework', description: 'Enforcement protocol definition', phase: 'execution', status: 'pending', owner: 'InfraX' },
    ],
  },
];

// ── Diligence reports ─────────────────────────────────────────────────────────
export const DILIGENCE_REPORTS: DiligenceReport[] = [
  {
    id: 'rep-001',
    assetName: 'Ashburn Core Campus',
    market: 'Northern Virginia',
    reportDate: '2026-04-10',
    feasibilityScore: 87,
    dataConfidence: 94,
    powerDeliverability: 91,
    expansionViability: 82,
    riskFactors: [
      { id: 'r-001', category: 'Grid', title: 'Substation Headroom', description: 'Dominion Energy reducing available headroom by 15% in Q3 2026.', level: 'medium', mitigations: ['Advance reservation recommended', 'Explore secondary substation options'] },
      { id: 'r-002', category: 'Market', title: 'Rate Compression Risk', description: 'NOVA market pricing elevated. Costs likely to increase 6–10% in 12 months.', level: 'low', mitigations: ['Lock 3-year pricing via LOI', 'Include CPI cap clause'] },
    ],
    highlights: ['Operational interconnect — no queue risk', 'Tier III redundancy verified', '6 carrier fiber routes confirmed'],
    redFlags: [],
    underwritingSummary: 'Asset presents a high-confidence, low-risk deployment opportunity. Recommend proceeding to LOI within 45 days to secure current pricing.',
    recommendedAction: 'proceed',
  },
  {
    id: 'rep-002',
    assetName: 'Irving Logistics District',
    market: 'Dallas-Fort Worth',
    reportDate: '2026-03-28',
    feasibilityScore: 62,
    dataConfidence: 79,
    powerDeliverability: 55,
    expansionViability: 88,
    riskFactors: [
      { id: 'r-003', category: 'Grid', title: 'ERCOT Interconnect Queue', description: 'Pending interconnect status with 14-month estimated timeline.', level: 'high', mitigations: ['Negotiate interim power arrangement', 'Validate queue position with Oncor'] },
      { id: 'r-004', category: 'Operational', title: 'Timeline Risk', description: '18-month delivery window exceeds typical deployment target.', level: 'medium', mitigations: ['Parallel-path alternative sites', 'Define contractual penalty structure'] },
    ],
    highlights: ['Large expansion capacity (220MW)', 'Low-cost market ($132/kW)', 'Strong operator track record'],
    redFlags: ['Interconnect pending — no grid commitment', 'Timeline exceeds 12-month threshold'],
    underwritingSummary: 'Asset has strong long-term expansion viability but carries material near-term grid risk. Recommend proceeding only with conditional terms tied to interconnect milestone.',
    recommendedAction: 'proceed-with-conditions',
  },
];

// ── Leadership ─────────────────────────────────────────────────────────────────
export const LEADERSHIP: Leader[] = [
  {
    id: 'l-001',
    name: 'Alexandra Mercer',
    role: 'Chief Executive Officer',
    bio: 'Former VP of Infrastructure Strategy at a Fortune 50 hyperscaler. 18 years structuring AI-scale deployments across North America, EMEA, and APAC. Led $4B+ in infrastructure mandates.',
    expertise: ['Strategic Deployment', 'Capital Formation', 'AI Infrastructure', 'Grid Strategy'],
    decisionDomains: ['Mandate Architecture', 'Capital Allocation', 'Client Relationships', 'Market Strategy'],
    background: ['JPMorgan Infrastructure Finance', 'AWS Infrastructure Planning', 'SAIC Grid Intelligence'],
  },
  {
    id: 'l-002',
    name: 'Marcus Okafor',
    role: 'Chief Technology Officer',
    bio: 'Power systems engineer with deep expertise in utility interconnection modeling and grid constraint analysis. Built the InfraAlign™ scoring engine from first principles. 15+ years at the intersection of power and compute.',
    expertise: ['Power Systems Engineering', 'InfraAlign™ Architecture', 'Interconnection Modeling', 'Constraint Analysis'],
    decisionDomains: ['Technical Validation', 'Scoring Engine', 'Data Architecture', 'Modeling Standards'],
    background: ['NERC Reliability Standards Committee', 'GE Grid Solutions', 'MIT Energy Initiative'],
  },
  {
    id: 'l-003',
    name: 'Diana Chen',
    role: 'Head of Capital Advisory',
    bio: 'Infrastructure investment specialist with $6B+ in data center transactions. Former managing director at a top-tier infrastructure fund. Designed the diligence framework now used by three sovereign wealth funds.',
    expertise: ['Infrastructure Finance', 'Due Diligence', 'Underwriting', 'Asset Valuation'],
    decisionDomains: ['Capital Advisory', 'Investor Relations', 'Diligence Standards', 'Risk Frameworks'],
    background: ['Macquarie Infrastructure', 'Brookfield Asset Management', 'Goldman Sachs Infrastructure'],
  },
  {
    id: 'l-004',
    name: 'James Whitfield',
    role: 'Head of Execution',
    bio: 'Veteran deployment operations leader. Managed 40+ hyperscale data center projects from permitting through commissioning. Built operator networks across 14 markets. Known for enforcing delivery accountability where others negotiate around it.',
    expertise: ['Deployment Operations', 'Operator Relations', 'SLA Enforcement', 'Risk Management'],
    decisionDomains: ['Execution Oversight', 'Operator Network', 'Delivery Accountability', 'Client Operations'],
    background: ['Digital Realty Operations', 'Turner Construction Technology', 'US Army Corps of Engineers'],
  },
];
